### ISSUE TITLE
[Feature Request] Mark homework as done

### ISSUE THREAD

**Issue by Zorby-dev** [ivanhrabcak/edupage-api#9]
Add the ability to mark homework as done, invisible, important (and liked?)

**Comment by ivanhrabcak** [comment]
Ok, I'll look into this.

**Comment by ivanhrabcak** [comment]
Hello! Today, I've added support for reactions. 
Unfortunately, marking a homework (or any other notification) as done, invisible or important isn't a reaction and it makes fetching notifications or doing anything else with them after marking them really hard. 
Because of this, I've only added like support, and I am not planning to add this feature (as it is really complex and I haven't found a way to fetch what marks a notification has).

Here's an example of how you could like a notification:
```python
from edupage_api import Edupage
import time 

edupage = Edupage("subdomain", "username", "password")
edupage.login()

notifications = edupage.get_notifications()
print(notification[0])

print(notifications[0].like()) # returns True on success, False on error
time.sleep(5)
print(notifications[0].remove_like()) # same here, this returns a boolean

```
